const tools = [
        {
            "Icon":[
                {
                    "name":"easyicon",
                    "imgSrcSrc":"@assets/img/WX20171112-134720.png",
                    "url":"http://www.easyicon.net/",
                    "description":"icon图标",
                    "tag":"icon"
                },
                {
                    "name":"IconFont",
                    "imgSrcSrc":"@assets/img/WX20171112-135146.png",
                    "url":"http://www.iconfont.cn/",
                    "description":"icon font",
                    "tag":"icon"
                },
                {
                    "name":"iconpng",
                    "imgSrcSrc":"@assets/img/WX20171112-135146.png",
                    "url":"http://www.iconpng.com/",
                    "description":"icon 支持中文搜索",
                    "tag":"icon"
                },
                {
                    "name":"icons8",
                    "imgSrcSrc":"@assets/imgSrc/WX20171112-135146.png",
                    "url":"https://icons8.com/",
                    "description":"拥有 42,800 个免费图标，提供各个平台的基础图标与分类图标，其特色是大小和颜色随意自定义。",
                    "tag":"icon"
                },
                {
                    "name":"iconfinder",
                    "imgSrcSrc":"@assets/imgSrc/WX20171112-135146.png",
                    "url":"https://www.iconfinder.com/",
                    "description":"哥本哈根一个团队做的 icon 专业图标网站，拥有 1563889 个图标和37058图标集，是最专业的 icon 图标网站之一",
                    "tag":"icon"
                },
                {
                    "name":"Noun Project",
                    "imgSrcSrc":"",
                    "url":"https://thenounproject.com/",
                    "description":"",
                    "tag":"icon"
                },
                {
                    "name":"FLATICON",
                    "imgSrcSrc":"",
                    "url":"https://www.flaticon.com/",
                    "description":"搜索海量扁平化图标，让图标搜索和转换变得非常简单和快速，并提供常用格式 SVG、PSD 源文件和 PNG 下载。",
                    "tag":"icon"
                },
                {
                    "name":"iconstore",
                    "imgSrcSrc":"",
                    "url":"https://iconstore.co/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"Material icons",
                    "imgSrcSrc":"",
                    "url":"",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"Material icons",
                    "imgSrc":"",
                    "url":"https://material.io/icons/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"swifticons",
                    "imgSrc":"",
                    "url":"https://www.swifticons.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"flat-icon-design",
                    "imgSrc":"",
                    "url":"http://flat-icon-design.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"fontawesome",
                    "imgSrc":"",
                    "url":"http://fontawesome.io/",
                    "description":"",
                    "tag":""
                }
            ]
        },
        {
            "PPT":[
            
            ]
        },
        {
            "COLORS":[
                {
                    "name":"peise",
                    "imgSrc":"",
                    "url":"http://www.peise.net/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"materialpalette",
                    "imgSrc":"",
                    "url":"https://www.materialpalette.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"coolors",
                    "imgSrc":"",
                    "url":"https://coolors.co/browser/latest/1",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"uigradients",
                    "imgSrc":"",
                    "url":"https://uigradients.com/#CrimsonTide",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"colorhunt",
                    "imgSrc":"",
                    "url":"http://colorhunt.co/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"color uisdc",
                    "imgSrc":"",
                    "url":"http://color.uisdc.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"colorfavs",
                    "imgSrc":"",
                    "url":"http://www.colorfavs.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"colordrop",
                    "imgSrc":"",
                    "url":"https://colordrop.io/",
                    "description":"",
                    "tag":""
                }
            ]
        },
        {
            "Design":[
                {
                    "name":"dribbble",
                    "imgSrc":"",
                    "url":"https://dribbble.com/",
                    "description":"",
                    "tag":"design"
                }
            ]
        },
        {
            "picture":[
                {
                    "name":"unsplash",
                    "imgSrc":"",
                    "url":"https://unsplash.com/",
                    "description":"",
                    "tag":"picture"
                },
                {
                    "name":"视觉中国",
                    "imgSrc":"",
                    "url":"https://www.vcg.com/creative",
                    "description":"",
                    "tag":"picture"
                },
                {
                    "name":"morguefile",
                    "imgSrc":"",
                    "url":"https://morguefile.com/",
                    "description":"",
                    "tag":"picture"
                },
                {
                    "name":"图虫",
                    "imgSrc":"",
                    "url":"https://tuchong.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"deviantart",
                    "imgSrc":"",
                    "url":"https://www.deviantart.com/",
                    "description":"动漫图片",
                    "tag":""
                },
                {
                    "name":"500px",
                    "imgSrc":"",
                    "url":"https://500px.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"全景图片",
                    "imgSrc":"",
                    "url":"http://www.quanjing.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"lofter",
                    "imgSrc":"",
                    "url":"http://www.lofter.com",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"freestockphotos",
                    "imgSrc":"",
                    "url":"http://www.freestockphotos.biz/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"photopin",
                    "imgSrc":"",
                    "url":"http://photopin.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"presentationzen",
                    "imgSrc":"",
                    "url":"http://www.presentationzen.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"wallhalla",
                    "imgSrc":"",
                    "url":"https://wallhalla.com/",
                    "description":"",
                    "tag":""
                }
            ]
        },
        {
            "IT news":[
                {
                    "name":"Hacker News",
                    "imgSrc":"",
                    "url":"https://news.ycombinator.com/news",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"EchoJs",
                    "imgSrc":"",
                    "url":"http://www.echojs.com/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"",
                    "imgSrc":"",
                    "url":"",
                    "description":"",
                    "tag":""
                }
            ]
        },
        {
            "manual":[
                {
                    "name":"linux",
                    "imgSrc":"",
                    "url":"http://man.linuxde.net/",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"webpack",
                    "imgSrc":"",
                    "url":"https://webpack.js.org",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"bash",
                    "imgSrc":"",
                    "url":"http://cn.linux.vbird.org/linux_basic/0320bash.php",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"git",
                    "imgSrc":"",
                    "url":"https://git-scm.com/book/zh/v2",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"es5",
                    "imgSrc":"",
                    "url":"http://www.ecma-international.org/ecma-262/5.1/index.html",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"es5",
                    "url":"http://es5.github.io/"
                },
                {
                    "name":"MDN",
                    "imgSrc":"",
                    "url":"https://developer.mozilla.org/zh-CN/docs/Web/Tutorials",
                    "description":"",
                    "tag":""
                },
                {
                    "name":"",
                    "imgSrc":"",
                    "url":"",
                    "description":"",
                    "tag":""
                }
            ]
        },
        {
            "online-tools":[
                {
                    "name":"JS Bin",
                    "url":"https://code.h5jun.com/yahi/1/edit?html,css,output"
                },
                {
                    "name":"dictionary.cambridge",
                    "url":"https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD/humiliate"
                },
                {
                    "name":"processon",
                    "url":"https://www.processon.com/diagrams"
                }
            ]
        },
        {
            "blog":[
                
            ]
        }
    ]


export default tools;